'use client'
import type {Connection,ShipPlan} from '@/lib/ships'
import {newPart,newId} from '@/lib/ships'
import {openingError,physicalOpening} from '@/lib/ship-openings'
export default function ShipOpeningEditor({plan,connection:c,disabled,onChange}:{plan:ShipPlan;connection:Connection;disabled:boolean;onChange:(plan:ShipPlan)=>void}){
 function patch(width:number,height:number,ladder:boolean){const from=plan.decks.find(d=>d.id===c.from_deck)!;let parts=[...plan.parts],id=c.aperture?.ladder_part_id??null;if(ladder&&!id){const p={...newPart(from,c.from),id:newId(),type:'Ladder',name:`${c.name} ladder`};parts.push(p);id=p.id}if(!ladder){parts=parts.filter(p=>p.id!==id);id=null;}const next={...plan,parts,connections:plan.connections.map(v=>v.id===c.id?{...v,aperture:{width,height,ladder_part_id:id}}:v)};onChange(next)}
 const error=openingError(plan)
 return <fieldset disabled={disabled} className="space-y-3 border-t border-gray-600 pt-3"><legend>Deck opening</legend><p className="text-xs text-gray-400">Openings cut the upper floor and lower ceiling. One cell is five feet. Join adjacent decks; use one opening per pair for a multi-level hold. Ladders are separate inventory fixtures anchored to the source endpoint.</p>{!c.aperture?<><p className="text-xs">Legacy link: {physicalOpening(plan,c)?'one-cell opening with a ladder':'travel retained; physical opening needs valid adjacent room endpoints'}.</p><button type="button" className="underline" onClick={()=>patch(1,1,true)}>Configure opening and ladder</button></>:<><div className="grid grid-cols-2 gap-2">{(['width','height'] as const).map(key=><label key={key} className="text-xs">Opening {key} (cells)<input aria-label={`Opening ${key}`} type="number" min={1} max={100} value={c.aperture![key]} onChange={e=>patch(key==='width'?Number(e.target.value):c.aperture!.width,key==='height'?Number(e.target.value):c.aperture!.height,!!c.aperture!.ladder_part_id)} className="block w-full bg-gray-950 border rounded p-2"/></label>)}</div><label className="block text-sm"><input aria-label="Opening has ladder" type="checkbox" checked={!!c.aperture.ladder_part_id} onChange={e=>patch(c.aperture!.width,c.aperture!.height,e.target.checked)}/> Ladder fixture</label>{!c.aperture.ladder_part_id&&<p className="text-xs text-gray-400">View-only opening: no deck travel. Open edges stop walking; no falling physics.</p>}</>}{error&&<p role="status" className="text-amber-200 text-xs">{error}</p>}</fieldset>
}
